### ISSUE TITLE
ERRO AO CARREGAR TABELA

### ISSUE THREAD

**Issue by MKOKABU** [rictom/cnpj-sqlite#15]
Bom dia, o script descompactou os arquivos, mas ocorre o seguinte erro a partir do carregamento da primeira tabela (CNAE):
carregando tabela C:\dados-publicos\F.K03200$Z.D30408.CNAECSV
Traceback (most recent call last):
  File "C:\Users\Tributos\Downloads\rede-cnpj-master\dados_cnpj_para_sqlite.py", line 50, in <module>
    carregaTabelaCodigo('.CNAECSV', 'cnae')
  File "C:\Users\Tributos\Downloads\rede-cnpj-master\dados_cnpj_para_sqlite.py", line 47, in carregaTabelaCodigo
    engine.execute(f'CREATE INDEX idx_{nomeTabela} ON {nomeTabela}(codigo);')
    ^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'execute'

Process finished with exit code 1

**Comment by dlimars** [comment]
Boa noite, tive um problema parecido

Estou utilizando `Python 3.9.13` e `sqlalchemy==1.4.47`, mesmo utilizando a versão mais recente do sqlalchemy

```
Traceback (most recent call last):
  File "/Volumes/Storage_Multilaser/cnpj/cnpj-sqlite/dados_cnpj_para_sqlite.py", line 50, in <module>
    carregaTabelaCodigo('.CNAECSV','cnae')
  File "/Volumes/Storage_Multilaser/cnpj/cnpj-sqlite/dados_cnpj_para_sqlite.py", line 44, in carregaTabelaCodigo
    arquivo = list(glob.glob(os.path.join(pasta_saida, '*' + extensaoArquivo)))[0]
IndexError: list index out of range
```
